In [1]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score

In [2]:
item_info_train = pd.read_csv('ItemInfo_train.csv/ItemInfo_train.csv')
item_pairs_train = pd.read_csv('ItemPairs_train.csv/ItemPairs_train.csv')
item_info_test = pd.read_csv('ItemInfo_test.csv/ItemInfo_test.csv')
item_pairs_test  = pd.read_csv('ItemPairs_test.csv/ItemPairs_test.csv')
category = pd.read_csv('Category.csv/Category.csv')
location  = pd.read_csv('Location.csv/Location.csv')

In [24]:
def prepare_train_test(df_info, df_pairs):
    merge_1 = pd.merge(left=df_pairs, right=df_info, left_on='itemID_1', right_on='itemID',how='inner')
    merge_2 = pd.merge(left=merge_1, right=df_info,left_on='itemID_2', right_on='itemID',how='inner')
    merge_2.drop(['itemID_x','images_array_x','itemID_y','images_array_y'],axis = 1,inplace=True)
    return(merge_2)

### Preparing train & test

In [25]:
train = prepare_train_test(item_info_train,item_pairs_train)
test = prepare_train_test(item_info_test,item_pairs_test)

### Handling missing values

In [5]:
def missing_values(df):
    df.title_x.dropna(inplace=True)
    df.description_x.fillna(value=pd.Series(test.title_x.values),inplace=True)
    df.description_y.fillna(value=pd.Series(test.title_y.values),inplace=True)
    df.drop(['images_array_x','attrsJSON_x','price_x','images_array_y','attrsJSON_y','price_y'],axis=1,inplace=True)
    return(df) 

In [6]:
def feature_add(df):
    df['title_len_x'] = [len(str(m)) for m in df.title_x.values]
    df['description_len_x'] = [len(str(m)) for m in df.description_x.values]
    df['title_len_y'] = [len(str(m)) for m in df.title_x.values]
    df['description_len_y'] = [len(str(m)) for m in df.description_y.values]
    df.drop(['title_x','title_y','description_x','description_y'],axis=1,inplace=True)
    return(df)

In [7]:
train = missing_values(train)
test = missing_values(test)

In [8]:
train = feature_add(train)
test = feature_add(test)

In [108]:
train.head(2)

itemID_1  itemID_2  generationMethod  categoryID_x  locationID_x  \
0         1   4112648                 1            81        648140   
1         3   1991275                 1            14        639040   

       lat_x      lon_x  categoryID_y  locationID_y      lat_y      lon_y  \
0  64.686946  30.815924            81        648140  64.686946  30.815924   
1  55.678037  37.256548            14        639040  55.678037  37.256548   

   title_len_x  title_len_y  description_len_x  description_len_y  
0           28           28                  7                  7  
1            9            9                  7                  7

### Training random forest on train dataset

In [41]:
rfc=RandomForestClassifier(n_estimators=1000)

In [10]:
y = train.isDuplicate
train.drop('isDuplicate',axis=1,inplace=True)

In [11]:
rfc.fit(train,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [12]:
rfc.feature_importances_

array([ 0.07861288,  0.0864356 ,  0.18976509,  0.0588853 ,  0.02623861,
        0.04123123,  0.03872553,  0.05885876,  0.02667046,  0.04126645,
        0.03927381,  0.05634325,  0.09657453,  0.05672616,  0.10439235])

In [13]:
rfc.classes_

array([0, 1], dtype=int64)

In [139]:
preds = rfc.predict_proba(test)[:,1]

In [151]:
submit = pd.DataFrame({'id':item_pairs_test.id.values,'probability':preds})

In [152]:
submit.to_csv('submit_28th_02.csv',index=None, header=True)

### Generating some more features

In [14]:
item_info_train = pd.read_csv('ItemInfo_train.csv/ItemInfo_train.csv')
item_pairs_train = pd.read_csv('ItemPairs_train.csv/ItemPairs_train.csv')
item_info_test = pd.read_csv('ItemInfo_test.csv/ItemInfo_test.csv')
item_pairs_test  = pd.read_csv('ItemPairs_test.csv/ItemPairs_test.csv')
category = pd.read_csv('Category.csv/Category.csv')
location  = pd.read_csv('Location.csv/Location.csv')

In [15]:
train = prepare_train_test(item_info_train,item_pairs_train)
test = prepare_train_test(item_info_test,item_pairs_test)

In [17]:
train.drop(['generationMethod','images_array_x', 'attrsJSON_x','images_array_y', 'attrsJSON_y'], axis=1,inplace=True)

In [19]:
test.drop(['id', 'images_array_x','attrsJSON_x', 'images_array_y','attrsJSON_y'],axis=1,inplace=True)

In [23]:
train['latitude_same'] = (train.lat_x == train.lat_y).astype(int)
train['longitude_same'] = (train.lon_x == train.lon_y).astype(int)
train['location_same'] = (train.locationID_x == train.locationID_y).astype(int)
train['price_minus'] = (train.price_x - train.price_y)
train['title_same'] = (train.title_x == train.title_y).astype(int)
train['description_same'] = (train.description_x == train.description_y).astype(int)
test['latitude_same'] = (test.lat_x == test.lat_y).astype(int)
test['longitude_same'] = (test.lon_x == test.lon_y).astype(int)
test['location_same'] = (test.locationID_x == test.locationID_y).astype(int)
test['price_minus'] = (test.price_x - test.price_y)
test['title_same'] = (test.title_x == test.title_y).astype(int)
test['description_same'] = (test.description_x == test.description_y).astype(int)

test.fillna(value=-999,inplace=True)
train.fillna(value=-999,inplace=True)

itemID_1  itemID_2  isDuplicate  categoryID_x  \
0               1   4112648            1            81   
1               3   1991275            1            14   
2               4   1223296            0            84   
3               7   1058851            1            84   
4               8   2161930            1            39   
5               9    694103            1            39   
6              12   5637025            0             9   
7          401724   5637025            1             9   
8         5279740   5637025            1             9   
9              12   5279740            0             9   
10        4721374   5279740            1             9   
11             15    113701            0            32   
12             16   2467698            0            27   
13             19   4538621            0            88   
14             19    380482            1            88   
15             20   3737377            0            27   
16        1298192   3737377            0            27   
17             20   4117359            0            27   
18        1298192   4117359            0            27   
19             20   2338340            0            27   
20        1298192   2338340            0            27   
21             21   3276771            1            29   
22        1211996   3276771            1            29   
23             22   2719041            1            27   
24             26   3226871            1            33   
25             26   3913671            0            33   
26             28   1356437            1            27   
27             29   1959141            1             9   
28             32   4156631            1            27   
29             33    512178            0            84   
...           ...       ...          ...           ...   
2991366   6076531   6111582            1            84   
2991367   6076853   6100159            1            19   
2991368   6077323   6107400            1            24   
2991369   6077717   6103751            1            39   
2991370   6079457   6092804            1            14   
2991371   6079902   6084541            1            20   
2991372   6079906   6101207            1           112   
2991373   6080669   6109092            1             9   
2991374   6080999   6105015            0            84   
2991375   6081022   6093209            1            19   
2991376   6081070   6106029            1            10   
2991377   6081856   6095264            1            10   
2991378   6084482   6110469            1           112   
2991379   6085309   6100334            1            20   
2991380   6086029   6087019            1            10   
2991381   6086278   6105989            0            83   
2991382   6088419   6095401            1            85   
2991383   6089096   6092147            1           114   
2991384   6089354   6094569            0            29   
2991385   6089405   6111381            1            27   
2991386   6089990   6099615            0            88   
2991387   6090665   6111628            1            27   
2991388   6096767   6098116            0            82   
2991389   6097921   6099438            1            24   
2991390   6098593   6104890            1           114   
2991391   6100664   6101171            0            10   
2991392   6101234   6105511            0           112   
2991393   6101382   6109873            0            24   
2991394   6104879   6111227            1            36   
2991395   6106239   6109219            1           105   

                                                   title_x  \
0                                        Продам Камаз 6520   
1                                                Yamaha r6   
2                                           iPhone 3gs 8gb   
3                      Xiaomi Mi4 3гб RAM + 16гб ROM белый   
4                                           Лыжные ботинки   
5                        Сноуборд ботинк

In [24]:
features = ['latitude_same', 'longitude_same', 'location_same', 'price_minus', 'title_same', 'description_same']

In [42]:
rfc.fit(train[features],train.isDuplicate.values)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [43]:
rfc.feature_importances_

array([ 0.02424023,  0.01915796,  0.01352403,  0.62765799,  0.29355183,
        0.02186796])

In [34]:
rfc.classes_

array([0, 1], dtype=int64)

In [44]:
preds_100=rfc.predict_proba(test[features])[:,1]

In [46]:
submit = pd.DataFrame({'id':item_pairs_test.id.values,'probability':preds_100})

In [47]:
submit.to_csv('submit_28_04.csv',index=False,header=True)

### Applying GBM 

In [48]:
from sklearn.ensemble import GradientBoostingClassifier

In [49]:
gbm = GradientBoostingClassifier(n_estimators=1000)

In [ ]:
gbm.fit(train[features], train.isDuplicate.values)

### Creating new feature from json column using key-value comparison

In [2]:
item_info_train = pd.read_csv('ItemInfo_train.csv/ItemInfo_train.csv')
item_pairs_train = pd.read_csv('ItemPairs_train.csv/ItemPairs_train.csv')
item_info_test = pd.read_csv('ItemInfo_test.csv/ItemInfo_test.csv')
item_pairs_test  = pd.read_csv('ItemPairs_test.csv/ItemPairs_test.csv')
category = pd.read_csv('Category.csv/Category.csv')
location  = pd.read_csv('Location.csv/Location.csv')

In [5]:
train = prepare_train_test(item_info_train,item_pairs_train)
test = prepare_train_test(item_info_test,item_pairs_test)